title: Abid Hasan
baseurl: "/resume/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "abidhasan.bh@outlook.com"
linkedin: "http://linkedin.com/in/nishorgo"
github: "https://github.com/nishorgo"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
